### ISSUE TITLE
Fix companion app opening as white screen

### ISSUE THREAD

**Issue by Mvb1122** [EtienneLamoureux/sc-trade-companion#16]
# Versions:
App: Release 0.1.0
Java version 19, 2022-09-20
Star Citizen version: 3.21.1

# Summary: 
When launching the application, it opens as a white box. While I'm not versed in this application's structure and everything to go along with it, I don't believe that this is the intended behavior, at least for the moment. Rather than a helpless instigation of an issue, I would like to offer assistance in solving this. I happen to have the next week off of school, and a bit of (now one-year-outdated) experience working with Java UI, so please let me know if you want help developing a UI. (Preferably message me on Discord, my username is micahb.dev)

![image](https://github.com/EtienneLamoureux/sc-trade-companion/assets/68322167/290a5502-dcab-42c4-bc82-4042cbc1f224)

**Comment by EtienneLamoureux** [comment]
Hi and thanks for the report!
This is "intended" for now, but will not stay blank in the future 😄 

The first setting that will be added to this page is described in #7. The GUI is Swing with a FlatLaf look-and-feel, if you did want to take a look. Everything is already in the gradle dependencies.
