### ISSUE TITLE
Only process Star Citizen screenshots

### ISSUE THREAD

**Issue by EtienneLamoureux** [EtienneLamoureux/sc-trade-companion#36]
# Situation
Pressing F3 process the current screen, whatever the content

# Results
1. Only process screenshots of the SC client
2. Other screenshots are neither processed nor saved

**Comment by terence626** [comment]
Pressing F3 does NOT currently take nor process a screenshot of the SC Client.  It snaps a screenshot and processes it from whatever is designated the PRIMARY monitor.

Having a settings/option to pick the screen/monitor/display to snap from would be highly desirable, especially for those that play SC on their secondary (or tertiary) monitor.

Thank you.

**Comment by terence626** [comment]
I just installed it again and remembered why I stopped using this.  It seems to capture only display #1, regardless of which screen the user plays SC on.  Without the option to set a display to capture screenshots on, it makes this utility very arduous to use.  Hopefully, this enhancement can be considered.  Thank you.

**Comment by EtienneLamoureux** [comment]
This is indeed a big issue. We'll address it.

**Comment by terence626** [comment]
Thank you!  Looking forward to being able to set which display number to use for the screenshots!
