### ISSUE TITLE
Add a setting to allow users to send a username when submitting data

### ISSUE THREAD

**Issue by EtienneLamoureux** [EtienneLamoureux/sc-trade-companion#7]

**Comment by Mvb1122** [comment]
I whipped up a UI for it, although the code is abhorrently toxic and needs reworking to deal with window scaling edge cases. 
![check box disabled](https://github.com/EtienneLamoureux/sc-trade-companion/assets/68322167/8035c9b3-adaf-454a-bb3b-0df8d8ef194a)
![check box enabled](https://github.com/EtienneLamoureux/sc-trade-companion/assets/68322167/700df9f7-ee0c-4f33-bdb5-603c60a89ae0)


It's currently in [my fork](https://github.com/Mvb1122/sc-trade-companion), where the username box can be accessed via the `CompanionGui.GetUsername()` method. You can get the checkbox via `CompanionGui.GetUsernameEnabled()`

Let me know if this is something you want and I can open a pull request for it. My changes were purely limited to the CompanionGui class and the localization files.

**Comment by EtienneLamoureux** [comment]
This is great! I'd love to get a PR.

**Comment by Mvb1122** [comment]
Thank you, I will open it now.
