### ISSUE TITLE
Setting to use a specific monitor or display please?

### ISSUE THREAD

**Issue by terence626** [EtienneLamoureux/sc-trade-companion#71]
Hi,

Can there be a setting/option available to use a specific monitor/display for capturing the screenshots please?

Thank you for this tool / ecosystem.  I've been trying to diligently upload the screenshots at every trade terminal I can access.  However, something has gotten VERY tedious for me.

I don't play SC on my primary monitor.  And it seems that this tool defaults to capturing screenshots on the primary monitor.  So EVERYTIME I wish to hit F3 to take a screenshot, I need to (beforehand) switch my primary monitor back to the one running SC.  Then after the 2-5 screenshots (on one terminal), I switch primary monitors back to my preference.

After using this tool for a few weeks, this monitor swapping back and forth has gotten so tedious, that sometimes I just don't feel like uploading screenshots sometimes.  And I don't wish to feel that way.

If the monitor/display option becomes available, this would GREATLY be appreciated.  Thank you for considering this feature!

**Comment by EtienneLamoureux** [comment]
Thank you for your suggestion. I'll link it to #36 and treat it as a single fix :)
