### ISSUE TITLE
Improve OCR on "illegal" color palette kiosks

### ISSUE THREAD

**Issue by Amegatron** [EtienneLamoureux/sc-trade-companion#72]
In most of the times, it either can't parse selected shop name or the commodities list. I tried with numerous screenshots at slightly different angles. It gives out either ERROR Code 5 or 6.
At the same time, it is sometimes successfull at parsing some of Sell options (under same angle).
![2024-05-27_00-20-09-173262800](https://github.com/EtienneLamoureux/sc-trade-companion/assets/6664497/0791fe44-9001-4bdd-96b9-49f0a908a85b)
![2024-05-27_00-20-58-34383100](https://github.com/EtienneLamoureux/sc-trade-companion/assets/6664497/634b0929-303b-427a-aec0-704fb5fd5b21)

**Comment by EtienneLamoureux** [comment]
https://github.com/EtienneLamoureux/sc-trade-companion/releases/tag/1.0.3 is improved on the new "red" kiosks.
