### ISSUE TITLE
Enable scrolling on the Logs tab

### ISSUE THREAD

**Issue by AQuietLurker** [EtienneLamoureux/sc-trade-companion#75]
It would be nice to have the logs automatically scroll to the newest message. That way we can ensure that the capture was successful, and sent properly.

Currently I have to exit the game window, and scroll the logs to the bottom to find out if my most recent scans were successfully parsed.

**Comment by EtienneLamoureux** [comment]
You can achieve the requested behavior by clicking twice on the "Time" column header, to sort them by "latest first" :)
